# Generated by Django 2.2.7 on 2019-12-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
